### ISSUE TITLE
Why is counter_test/counter_basys3.v?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-examples#11] opened 2020-06-08 22:29 UTC
Shouldn't it be `counter_test/counter.v`?

**Comment by mithro** [comment] 2020-06-08 22:33
FYI - @joannabrozek

**Comment by pgielda** [comment] 2020-06-08 22:40
I guess its because it, as README states "targets the Basys3 board".
it would still make sense to just rename it for simplicity.

**Comment by mithro** [comment] 2020-06-08 23:25
@pgielda Most certainly want to add Arty support too...

**Comment by pgielda** [comment] 2020-06-09 22:01
it is renamed now at least.

**Comment by pgielda** [comment] 2020-06-09 22:01
I guess its now a duplicate of #6

**Closed by pgielda** 2020-06-09 22:01 UTC
